name: "Test"
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop -c ci/build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: main.bc.js
        path: _build/default/bin/main.bc.js

