name: "Deploy"
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
  # push:
  #   branches:
  #     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    - run: nix develop -c ci/build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: main.bc.js
        path: _build/default/bin/main.bc.js
    - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

