name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
      nix develop
      opam switch create . --deps-only --locked
      dune build bin/main.bc.js
    - uses: actions/upload-artifact@v4
      with:
        name: main.bc.js
        path: _build/default/bin/main.bc.js

